typedef unsignedlong GLenum;
typedef boolean GLboolean;
typedef unsignedlong GLbitfield;
typedef byte GLbyte;
typedef short GLshort;
typedef long GLint;
typedef long GLsizei;
typedef long long GLintptr;
typedef long long GLsizeiptr;
typedef octet GLubyte;
typedef unsignedshort GLushort;
typedef unsignedlong GLuint;
typedef unrestricted float GLfloat;
typedef unrestricted float GLclampf;
dictionary WebGLContextAttributes  {
    GLboolean alpha = true;
    GLboolean depth = true;
    GLboolean stencil = false;
    GLboolean antialias = true;
    GLboolean premultipliedAlpha = true;
    GLboolean preserveDrawingBuffer = false;
    GLboolean preferLowPowerToHighPerformance = false;
    GLboolean failIfMajorPerformanceCaveat = false;
};
interface WebGLObject  {

};
interface WebGLBuffer : WebGLObject {

};
interface WebGLFramebuffer : WebGLObject {

};
interface WebGLProgram : WebGLObject {

};
interface WebGLRenderbuffer : WebGLObject {

};
interface WebGLShader : WebGLObject {

};
interface WebGLTexture : WebGLObject {

};
interface WebGLUniformLocation  {

};
interface WebGLActiveInfo  {
    readonly attribute GLint size;
    readonly attribute GLenum type;
    readonly attribute DOMString name;
};
interface WebGLShaderPrecisionFormat  {
    readonly attribute GLint rangeMin;
    readonly attribute GLint rangeMax;
    readonly attribute GLint precision;
};
[NoInterfaceObject]
interface WebGLRenderingContextBase  {
    const GLenum DEPTH_BUFFER_BIT = 256;
    const GLenum STENCIL_BUFFER_BIT = 1024;
    const GLenum COLOR_BUFFER_BIT = 16384;
    const GLenum POINTS = 0;
    const GLenum LINES = 1;
    const GLenum LINE_LOOP = 2;
    const GLenum LINE_STRIP = 3;
    const GLenum TRIANGLES = 4;
    const GLenum TRIANGLE_STRIP = 5;
    const GLenum TRIANGLE_FAN = 6;
    const GLenum ZERO = 0;
    const GLenum ONE = 1;
    const GLenum SRC_COLOR = 768;
    const GLenum ONE_MINUS_SRC_COLOR = 769;
    const GLenum SRC_ALPHA = 770;
    const GLenum ONE_MINUS_SRC_ALPHA = 771;
    const GLenum DST_ALPHA = 772;
    const GLenum ONE_MINUS_DST_ALPHA = 773;
    const GLenum DST_COLOR = 774;
    const GLenum ONE_MINUS_DST_COLOR = 775;
    const GLenum SRC_ALPHA_SATURATE = 776;
    const GLenum FUNC_ADD = 32774;
    const GLenum BLEND_EQUATION = 32777;
    const GLenum BLEND_EQUATION_RGB = 32777;
    const GLenum BLEND_EQUATION_ALPHA = 34877;
    const GLenum FUNC_SUBTRACT = 32778;
    const GLenum FUNC_REVERSE_SUBTRACT = 32779;
    const GLenum BLEND_DST_RGB = 32968;
    const GLenum BLEND_SRC_RGB = 32969;
    const GLenum BLEND_DST_ALPHA = 32970;
    const GLenum BLEND_SRC_ALPHA = 32971;
    const GLenum CONSTANT_COLOR = 32769;
    const GLenum ONE_MINUS_CONSTANT_COLOR = 32770;
    const GLenum CONSTANT_ALPHA = 32771;
    const GLenum ONE_MINUS_CONSTANT_ALPHA = 32772;
    const GLenum BLEND_COLOR = 32773;
    const GLenum ARRAY_BUFFER = 34962;
    const GLenum ELEMENT_ARRAY_BUFFER = 34963;
    const GLenum ARRAY_BUFFER_BINDING = 34964;
    const GLenum ELEMENT_ARRAY_BUFFER_BINDING = 34965;
    const GLenum STREAM_DRAW = 35040;
    const GLenum STATIC_DRAW = 35044;
    const GLenum DYNAMIC_DRAW = 35048;
    const GLenum BUFFER_SIZE = 34660;
    const GLenum BUFFER_USAGE = 34661;
    const GLenum CURRENT_VERTEX_ATTRIB = 34342;
    const GLenum FRONT = 1028;
    const GLenum BACK = 1029;
    const GLenum FRONT_AND_BACK = 1032;
    const GLenum CULL_FACE = 2884;
    const GLenum BLEND = 3042;
    const GLenum DITHER = 3024;
    const GLenum STENCIL_TEST = 2960;
    const GLenum DEPTH_TEST = 2929;
    const GLenum SCISSOR_TEST = 3089;
    const GLenum POLYGON_OFFSET_FILL = 32823;
    const GLenum SAMPLE_ALPHA_TO_COVERAGE = 32926;
    const GLenum SAMPLE_COVERAGE = 32928;
    const GLenum NO_ERROR = 0;
    const GLenum INVALID_ENUM = 1280;
    const GLenum INVALID_VALUE = 1281;
    const GLenum INVALID_OPERATION = 1282;
    const GLenum OUT_OF_MEMORY = 1285;
    const GLenum CW = 2304;
    const GLenum CCW = 2305;
    const GLenum LINE_WIDTH = 2849;
    const GLenum ALIASED_POINT_SIZE_RANGE = 33901;
    const GLenum ALIASED_LINE_WIDTH_RANGE = 33902;
    const GLenum CULL_FACE_MODE = 2885;
    const GLenum FRONT_FACE = 2886;
    const GLenum DEPTH_RANGE = 2928;
    const GLenum DEPTH_WRITEMASK = 2930;
    const GLenum DEPTH_CLEAR_VALUE = 2931;
    const GLenum DEPTH_FUNC = 2932;
    const GLenum STENCIL_CLEAR_VALUE = 2961;
    const GLenum STENCIL_FUNC = 2962;
    const GLenum STENCIL_FAIL = 2964;
    const GLenum STENCIL_PASS_DEPTH_FAIL = 2965;
    const GLenum STENCIL_PASS_DEPTH_PASS = 2966;
    const GLenum STENCIL_REF = 2967;
    const GLenum STENCIL_VALUE_MASK = 2963;
    const GLenum STENCIL_WRITEMASK = 2968;
    const GLenum STENCIL_BACK_FUNC = 34816;
    const GLenum STENCIL_BACK_FAIL = 34817;
    const GLenum STENCIL_BACK_PASS_DEPTH_FAIL = 34818;
    const GLenum STENCIL_BACK_PASS_DEPTH_PASS = 34819;
    const GLenum STENCIL_BACK_REF = 36003;
    const GLenum STENCIL_BACK_VALUE_MASK = 36004;
    const GLenum STENCIL_BACK_WRITEMASK = 36005;
    const GLenum VIEWPORT = 2978;
    const GLenum SCISSOR_BOX = 3088;
    const GLenum COLOR_CLEAR_VALUE = 3106;
    const GLenum COLOR_WRITEMASK = 3107;
    const GLenum UNPACK_ALIGNMENT = 3317;
    const GLenum PACK_ALIGNMENT = 3333;
    const GLenum MAX_TEXTURE_SIZE = 3379;
    const GLenum MAX_VIEWPORT_DIMS = 3386;
    const GLenum SUBPIXEL_BITS = 3408;
    const GLenum RED_BITS = 3410;
    const GLenum GREEN_BITS = 3411;
    const GLenum BLUE_BITS = 3412;
    const GLenum ALPHA_BITS = 3413;
    const GLenum DEPTH_BITS = 3414;
    const GLenum STENCIL_BITS = 3415;
    const GLenum POLYGON_OFFSET_UNITS = 10752;
    const GLenum POLYGON_OFFSET_FACTOR = 32824;
    const GLenum TEXTURE_BINDING_2D = 32873;
    const GLenum SAMPLE_BUFFERS = 32936;
    const GLenum SAMPLES = 32937;
    const GLenum SAMPLE_COVERAGE_VALUE = 32938;
    const GLenum SAMPLE_COVERAGE_INVERT = 32939;
    const GLenum COMPRESSED_TEXTURE_FORMATS = 34467;
    const GLenum DONT_CARE = 4352;
    const GLenum FASTEST = 4353;
    const GLenum NICEST = 4354;
    const GLenum GENERATE_MIPMAP_HINT = 33170;
    const GLenum BYTE = 5120;
    const GLenum UNSIGNED_BYTE = 5121;
    const GLenum SHORT = 5122;
    const GLenum UNSIGNED_SHORT = 5123;
    const GLenum INT = 5124;
    const GLenum UNSIGNED_INT = 5125;
    const GLenum FLOAT = 5126;
    const GLenum DEPTH_COMPONENT = 6402;
    const GLenum ALPHA = 6406;
    const GLenum RGB = 6407;
    const GLenum RGBA = 6408;
    const GLenum LUMINANCE = 6409;
    const GLenum LUMINANCE_ALPHA = 6410;
    const GLenum UNSIGNED_SHORT_4_4_4_4 = 32819;
    const GLenum UNSIGNED_SHORT_5_5_5_1 = 32820;
    const GLenum UNSIGNED_SHORT_5_6_5 = 33635;
    const GLenum FRAGMENT_SHADER = 35632;
    const GLenum VERTEX_SHADER = 35633;
    const GLenum MAX_VERTEX_ATTRIBS = 34921;
    const GLenum MAX_VERTEX_UNIFORM_VECTORS = 36347;
    const GLenum MAX_VARYING_VECTORS = 36348;
    const GLenum MAX_COMBINED_TEXTURE_IMAGE_UNITS = 35661;
    const GLenum MAX_VERTEX_TEXTURE_IMAGE_UNITS = 35660;
    const GLenum MAX_TEXTURE_IMAGE_UNITS = 34930;
    const GLenum MAX_FRAGMENT_UNIFORM_VECTORS = 36349;
    const GLenum SHADER_TYPE = 35663;
    const GLenum DELETE_STATUS = 35712;
    const GLenum LINK_STATUS = 35714;
    const GLenum VALIDATE_STATUS = 35715;
    const GLenum ATTACHED_SHADERS = 35717;
    const GLenum ACTIVE_UNIFORMS = 35718;
    const GLenum ACTIVE_ATTRIBUTES = 35721;
    const GLenum SHADING_LANGUAGE_VERSION = 35724;
    const GLenum CURRENT_PROGRAM = 35725;
    const GLenum NEVER = 512;
    const GLenum LESS = 513;
    const GLenum EQUAL = 514;
    const GLenum LEQUAL = 515;
    const GLenum GREATER = 516;
    const GLenum NOTEQUAL = 517;
    const GLenum GEQUAL = 518;
    const GLenum ALWAYS = 519;
    const GLenum KEEP = 7680;
    const GLenum REPLACE = 7681;
    const GLenum INCR = 7682;
    const GLenum DECR = 7683;
    const GLenum INVERT = 5386;
    const GLenum INCR_WRAP = 34055;
    const GLenum DECR_WRAP = 34056;
    const GLenum VENDOR = 7936;
    const GLenum RENDERER = 7937;
    const GLenum VERSION = 7938;
    const GLenum NEAREST = 9728;
    const GLenum LINEAR = 9729;
    const GLenum NEAREST_MIPMAP_NEAREST = 9984;
    const GLenum LINEAR_MIPMAP_NEAREST = 9985;
    const GLenum NEAREST_MIPMAP_LINEAR = 9986;
    const GLenum LINEAR_MIPMAP_LINEAR = 9987;
    const GLenum TEXTURE_MAG_FILTER = 10240;
    const GLenum TEXTURE_MIN_FILTER = 10241;
    const GLenum TEXTURE_WRAP_S = 10242;
    const GLenum TEXTURE_WRAP_T = 10243;
    const GLenum TEXTURE_2D = 3553;
    const GLenum TEXTURE = 5890;
    const GLenum TEXTURE_CUBE_MAP = 34067;
    const GLenum TEXTURE_BINDING_CUBE_MAP = 34068;
    const GLenum TEXTURE_CUBE_MAP_POSITIVE_X = 34069;
    const GLenum TEXTURE_CUBE_MAP_NEGATIVE_X = 34070;
    const GLenum TEXTURE_CUBE_MAP_POSITIVE_Y = 34071;
    const GLenum TEXTURE_CUBE_MAP_NEGATIVE_Y = 34072;
    const GLenum TEXTURE_CUBE_MAP_POSITIVE_Z = 34073;
    const GLenum TEXTURE_CUBE_MAP_NEGATIVE_Z = 34074;
    const GLenum MAX_CUBE_MAP_TEXTURE_SIZE = 34076;
    const GLenum TEXTURE0 = 33984;
    const GLenum TEXTURE1 = 33985;
    const GLenum TEXTURE2 = 33986;
    const GLenum TEXTURE3 = 33987;
    const GLenum TEXTURE4 = 33988;
    const GLenum TEXTURE5 = 33989;
    const GLenum TEXTURE6 = 33990;
    const GLenum TEXTURE7 = 33991;
    const GLenum TEXTURE8 = 33992;
    const GLenum TEXTURE9 = 33993;
    const GLenum TEXTURE10 = 33994;
    const GLenum TEXTURE11 = 33995;
    const GLenum TEXTURE12 = 33996;
    const GLenum TEXTURE13 = 33997;
    const GLenum TEXTURE14 = 33998;
    const GLenum TEXTURE15 = 33999;
    const GLenum TEXTURE16 = 34000;
    const GLenum TEXTURE17 = 34001;
    const GLenum TEXTURE18 = 34002;
    const GLenum TEXTURE19 = 34003;
    const GLenum TEXTURE20 = 34004;
    const GLenum TEXTURE21 = 34005;
    const GLenum TEXTURE22 = 34006;
    const GLenum TEXTURE23 = 34007;
    const GLenum TEXTURE24 = 34008;
    const GLenum TEXTURE25 = 34009;
    const GLenum TEXTURE26 = 34010;
    const GLenum TEXTURE27 = 34011;
    const GLenum TEXTURE28 = 34012;
    const GLenum TEXTURE29 = 34013;
    const GLenum TEXTURE30 = 34014;
    const GLenum TEXTURE31 = 34015;
    const GLenum ACTIVE_TEXTURE = 34016;
    const GLenum REPEAT = 10497;
    const GLenum CLAMP_TO_EDGE = 33071;
    const GLenum MIRRORED_REPEAT = 33648;
    const GLenum FLOAT_VEC2 = 35664;
    const GLenum FLOAT_VEC3 = 35665;
    const GLenum FLOAT_VEC4 = 35666;
    const GLenum INT_VEC2 = 35667;
    const GLenum INT_VEC3 = 35668;
    const GLenum INT_VEC4 = 35669;
    const GLenum BOOL = 35670;
    const GLenum BOOL_VEC2 = 35671;
    const GLenum BOOL_VEC3 = 35672;
    const GLenum BOOL_VEC4 = 35673;
    const GLenum FLOAT_MAT2 = 35674;
    const GLenum FLOAT_MAT3 = 35675;
    const GLenum FLOAT_MAT4 = 35676;
    const GLenum SAMPLER_2D = 35678;
    const GLenum SAMPLER_CUBE = 35680;
    const GLenum VERTEX_ATTRIB_ARRAY_ENABLED = 34338;
    const GLenum VERTEX_ATTRIB_ARRAY_SIZE = 34339;
    const GLenum VERTEX_ATTRIB_ARRAY_STRIDE = 34340;
    const GLenum VERTEX_ATTRIB_ARRAY_TYPE = 34341;
    const GLenum VERTEX_ATTRIB_ARRAY_NORMALIZED = 34922;
    const GLenum VERTEX_ATTRIB_ARRAY_POINTER = 34373;
    const GLenum VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 34975;
    const GLenum IMPLEMENTATION_COLOR_READ_TYPE = 35738;
    const GLenum IMPLEMENTATION_COLOR_READ_FORMAT = 35739;
    const GLenum COMPILE_STATUS = 35713;
    const GLenum LOW_FLOAT = 36336;
    const GLenum MEDIUM_FLOAT = 36337;
    const GLenum HIGH_FLOAT = 36338;
    const GLenum LOW_INT = 36339;
    const GLenum MEDIUM_INT = 36340;
    const GLenum HIGH_INT = 36341;
    const GLenum FRAMEBUFFER = 36160;
    const GLenum RENDERBUFFER = 36161;
    const GLenum RGBA4 = 32854;
    const GLenum RGB5_A1 = 32855;
    const GLenum RGB565 = 36194;
    const GLenum DEPTH_COMPONENT16 = 33189;
    const GLenum STENCIL_INDEX = 6401;
    const GLenum STENCIL_INDEX8 = 36168;
    const GLenum DEPTH_STENCIL = 34041;
    const GLenum RENDERBUFFER_WIDTH = 36162;
    const GLenum RENDERBUFFER_HEIGHT = 36163;
    const GLenum RENDERBUFFER_INTERNAL_FORMAT = 36164;
    const GLenum RENDERBUFFER_RED_SIZE = 36176;
    const GLenum RENDERBUFFER_GREEN_SIZE = 36177;
    const GLenum RENDERBUFFER_BLUE_SIZE = 36178;
    const GLenum RENDERBUFFER_ALPHA_SIZE = 36179;
    const GLenum RENDERBUFFER_DEPTH_SIZE = 36180;
    const GLenum RENDERBUFFER_STENCIL_SIZE = 36181;
    const GLenum FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 36048;
    const GLenum FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 36049;
    const GLenum FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 36050;
    const GLenum FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 36051;
    const GLenum COLOR_ATTACHMENT0 = 36064;
    const GLenum DEPTH_ATTACHMENT = 36096;
    const GLenum STENCIL_ATTACHMENT = 36128;
    const GLenum DEPTH_STENCIL_ATTACHMENT = 33306;
    const GLenum NONE = 0;
    const GLenum FRAMEBUFFER_COMPLETE = 36053;
    const GLenum FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 36054;
    const GLenum FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 36055;
    const GLenum FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 36057;
    const GLenum FRAMEBUFFER_UNSUPPORTED = 36061;
    const GLenum FRAMEBUFFER_BINDING = 36006;
    const GLenum RENDERBUFFER_BINDING = 36007;
    const GLenum MAX_RENDERBUFFER_SIZE = 34024;
    const GLenum INVALID_FRAMEBUFFER_OPERATION = 1286;
    const GLenum UNPACK_FLIP_Y_WEBGL = 37440;
    const GLenum UNPACK_PREMULTIPLY_ALPHA_WEBGL = 37441;
    const GLenum CONTEXT_LOST_WEBGL = 37442;
    const GLenum UNPACK_COLORSPACE_CONVERSION_WEBGL = 37443;
    const GLenum BROWSER_DEFAULT_WEBGL = 37444;
    readonly attribute HTMLCanvasElement canvas;
    readonly attribute GLsizei drawingBufferWidth;
    readonly attribute GLsizei drawingBufferHeight;
    [WebGLHandlesContextLoss] WebGLContextAttributes? getContextAttributes();
    [WebGLHandlesContextLoss] boolean isContextLost();
    sequence<DOMString>? getSupportedExtensions();
    object? getExtension(DOMString name);
    void activeTexture(GLenum texture);
    void attachShader(WebGLProgram? program, WebGLShader? shader);
    void bindAttribLocation(WebGLProgram? program, GLuint index, DOMString name);
    void bindBuffer(GLenum target, WebGLBuffer? buffer);
    void bindFramebuffer(GLenum target, WebGLFramebuffer? framebuffer);
    void bindRenderbuffer(GLenum target, WebGLRenderbuffer? renderbuffer);
    void bindTexture(GLenum target, WebGLTexture? texture);
    void blendColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
    void blendEquation(GLenum mode);
    void blendEquationSeparate(GLenum modeRGB, GLenum modeAlpha);
    void blendFunc(GLenum sfactor, GLenum dfactor);
    void blendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
    void bufferData(GLenum target, GLsizeiptr size, GLenum usage);
    void bufferData(GLenum target, BufferDataSource? data, GLenum usage);
    void bufferSubData(GLenum target, GLintptr offset, BufferDataSource? data);
    [WebGLHandlesContextLoss] GLenum checkFramebufferStatus(GLenum target);
    void clear(GLbitfield mask);
    void clearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
    void clearDepth(GLclampf depth);
    void clearStencil(GLint s);
    void colorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
    void compileShader(WebGLShader? shader);
    void compressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, ArrayBufferView data);
    void compressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, ArrayBufferView data);
    void copyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
    void copyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
    WebGLBuffer? createBuffer();
    WebGLFramebuffer? createFramebuffer();
    WebGLProgram? createProgram();
    WebGLRenderbuffer? createRenderbuffer();
    WebGLShader? createShader(GLenum type);
    WebGLTexture? createTexture();
    void cullFace(GLenum mode);
    void deleteBuffer(WebGLBuffer? buffer);
    void deleteFramebuffer(WebGLFramebuffer? framebuffer);
    void deleteProgram(WebGLProgram? program);
    void deleteRenderbuffer(WebGLRenderbuffer? renderbuffer);
    void deleteShader(WebGLShader? shader);
    void deleteTexture(WebGLTexture? texture);
    void depthFunc(GLenum func);
    void depthMask(GLboolean flag);
    void depthRange(GLclampf zNear, GLclampf zFar);
    void detachShader(WebGLProgram? program, WebGLShader? shader);
    void disable(GLenum cap);
    void disableVertexAttribArray(GLuint index);
    void drawArrays(GLenum mode, GLint first, GLsizei count);
    void drawElements(GLenum mode, GLsizei count, GLenum type, GLintptr offset);
    void enable(GLenum cap);
    void enableVertexAttribArray(GLuint index);
    void finish();
    void flush();
    void framebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, WebGLRenderbuffer? renderbuffer);
    void framebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, WebGLTexture? texture, GLint level);
    void frontFace(GLenum mode);
    void generateMipmap(GLenum target);
    WebGLActiveInfo? getActiveAttrib(WebGLProgram? program, GLuint index);
    WebGLActiveInfo? getActiveUniform(WebGLProgram? program, GLuint index);
    sequence<WebGLShader>? getAttachedShaders(WebGLProgram? program);
    [WebGLHandlesContextLoss] GLint getAttribLocation(WebGLProgram? program, DOMString name);
    any getBufferParameter(GLenum target, GLenum pname);
    any getParameter(GLenum pname);
    [WebGLHandlesContextLoss] GLenum getError();
    any getFramebufferAttachmentParameter(GLenum target, GLenum attachment, GLenum pname);
    any getProgramParameter(WebGLProgram? program, GLenum pname);
    DOMString? getProgramInfoLog(WebGLProgram? program);
    any getRenderbufferParameter(GLenum target, GLenum pname);
    any getShaderParameter(WebGLShader? shader, GLenum pname);
    WebGLShaderPrecisionFormat? getShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype);
    DOMString? getShaderInfoLog(WebGLShader? shader);
    DOMString? getShaderSource(WebGLShader? shader);
    any getTexParameter(GLenum target, GLenum pname);
    any getUniform(WebGLProgram? program, WebGLUniformLocation? location);
    WebGLUniformLocation? getUniformLocation(WebGLProgram? program, DOMString name);
    any getVertexAttrib(GLuint index, GLenum pname);
    [WebGLHandlesContextLoss] GLsizeiptr getVertexAttribOffset(GLuint index, GLenum pname);
    void hint(GLenum target, GLenum mode);
    [WebGLHandlesContextLoss] GLboolean isBuffer(WebGLBuffer? buffer);
    [WebGLHandlesContextLoss] GLboolean isEnabled(GLenum cap);
    [WebGLHandlesContextLoss] GLboolean isFramebuffer(WebGLFramebuffer? framebuffer);
    [WebGLHandlesContextLoss] GLboolean isProgram(WebGLProgram? program);
    [WebGLHandlesContextLoss] GLboolean isRenderbuffer(WebGLRenderbuffer? renderbuffer);
    [WebGLHandlesContextLoss] GLboolean isShader(WebGLShader? shader);
    [WebGLHandlesContextLoss] GLboolean isTexture(WebGLTexture? texture);
    void lineWidth(GLfloat width);
    void linkProgram(WebGLProgram? program);
    void pixelStorei(GLenum pname, GLint param);
    void polygonOffset(GLfloat factor, GLfloat units);
    void readPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, ArrayBufferView? pixels);
    void renderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
    void sampleCoverage(GLclampf value, GLboolean invert);
    void scissor(GLint x, GLint y, GLsizei width, GLsizei height);
    void shaderSource(WebGLShader? shader, DOMString source);
    void stencilFunc(GLenum func, GLint ref, GLuint mask);
    void stencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask);
    void stencilMask(GLuint mask);
    void stencilMaskSeparate(GLenum face, GLuint mask);
    void stencilOp(GLenum fail, GLenum zfail, GLenum zpass);
    void stencilOpSeparate(GLenum face, GLenum fail, GLenum zfail, GLenum zpass);
    void texImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, ArrayBufferView? pixels);
    void texImage2D(GLenum target, GLint level, GLenum internalformat, GLenum format, GLenum type, TexImageSource? source);
    void texParameterf(GLenum target, GLenum pname, GLfloat param);
    void texParameteri(GLenum target, GLenum pname, GLint param);
    void texSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, ArrayBufferView? pixels);
    void texSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLenum format, GLenum type, TexImageSource? source);
    void uniform1f(WebGLUniformLocation? location, GLfloat x);
    void uniform1fv(WebGLUniformLocation? location, Float32Array v);
    void uniform1fv(WebGLUniformLocation? location, sequence<GLfloat> v);
    void uniform1i(WebGLUniformLocation? location, GLint x);
    void uniform1iv(WebGLUniformLocation? location, Int32Array v);
    void uniform1iv(WebGLUniformLocation? location, sequence<long> v);
    void uniform2f(WebGLUniformLocation? location, GLfloat x, GLfloat y);
    void uniform2fv(WebGLUniformLocation? location, Float32Array v);
    void uniform2fv(WebGLUniformLocation? location, sequence<GLfloat> v);
    void uniform2i(WebGLUniformLocation? location, GLint x, GLint y);
    void uniform2iv(WebGLUniformLocation? location, Int32Array v);
    void uniform2iv(WebGLUniformLocation? location, sequence<long> v);
    void uniform3f(WebGLUniformLocation? location, GLfloat x, GLfloat y, GLfloat z);
    void uniform3fv(WebGLUniformLocation? location, Float32Array v);
    void uniform3fv(WebGLUniformLocation? location, sequence<GLfloat> v);
    void uniform3i(WebGLUniformLocation? location, GLint x, GLint y, GLint z);
    void uniform3iv(WebGLUniformLocation? location, Int32Array v);
    void uniform3iv(WebGLUniformLocation? location, sequence<long> v);
    void uniform4f(WebGLUniformLocation? location, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
    void uniform4fv(WebGLUniformLocation? location, Float32Array v);
    void uniform4fv(WebGLUniformLocation? location, sequence<GLfloat> v);
    void uniform4i(WebGLUniformLocation? location, GLint x, GLint y, GLint z, GLint w);
    void uniform4iv(WebGLUniformLocation? location, Int32Array v);
    void uniform4iv(WebGLUniformLocation? location, sequence<long> v);
    void uniformMatrix2fv(WebGLUniformLocation? location, GLboolean transpose, Float32Array value);
    void uniformMatrix2fv(WebGLUniformLocation? location, GLboolean transpose, sequence<GLfloat> value);
    void uniformMatrix3fv(WebGLUniformLocation? location, GLboolean transpose, Float32Array value);
    void uniformMatrix3fv(WebGLUniformLocation? location, GLboolean transpose, sequence<GLfloat> value);
    void uniformMatrix4fv(WebGLUniformLocation? location, GLboolean transpose, Float32Array value);
    void uniformMatrix4fv(WebGLUniformLocation? location, GLboolean transpose, sequence<GLfloat> value);
    void useProgram(WebGLProgram? program);
    void validateProgram(WebGLProgram? program);
    void vertexAttrib1f(GLuint indx, GLfloat x);
    void vertexAttrib1fv(GLuint indx, Float32Array values);
    void vertexAttrib1fv(GLuint indx, sequence<GLfloat> values);
    void vertexAttrib2f(GLuint indx, GLfloat x, GLfloat y);
    void vertexAttrib2fv(GLuint indx, Float32Array values);
    void vertexAttrib2fv(GLuint indx, sequence<GLfloat> values);
    void vertexAttrib3f(GLuint indx, GLfloat x, GLfloat y, GLfloat z);
    void vertexAttrib3fv(GLuint indx, Float32Array values);
    void vertexAttrib3fv(GLuint indx, sequence<GLfloat> values);
    void vertexAttrib4f(GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
    void vertexAttrib4fv(GLuint indx, Float32Array values);
    void vertexAttrib4fv(GLuint indx, sequence<GLfloat> values);
    void vertexAttribPointer(GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, GLintptr offset);
    void viewport(GLint x, GLint y, GLsizei width, GLsizei height);
};
interface WebGLRenderingContext  {

};
WebGLRenderingContext implements WebGLRenderingContextBase;
